tags:
  name: BMI
  description: BMI Controller

definitions:
  Target:
    type: object
    required:
      - height
      - weight
      - targetBody
      - activityType
    properties:
      height:
        type: string
        description: 키
      weight:
        type: string
        description: 몸무게
      targetBody:
        type: string
        description: 선호체형
      activityType:
        type: string
        description: 활동성

/bmi/target:
  post:
    tags: [BMI]
    produces:
      - application/json
    consumes:
      - application/json
    security:
      - bearerAuth: []
    requestBody:
      content:
        application/json:
          name: Target
          required: true
          schema:
            $ref: '#/definitions/Target'
    responses:
      201:
        description: 'bmi 등록 완료'
        content:
          application/json:
            example:
              status: 201
              message: '정상적으로 BMI가 저장되었습니다.'
      400:
        description: '잘못된 데이터를 입력한 경우'
        content:
          application/json:
            example:
              errorCode:
                status: 400
                message: '몸무게는 30이상 300 미만의 숫자로 입력해주세요. | 키는 50이상 350 미만의 숫자로 입력해주세요. |  체형 타입의 형식에 맞게 입력해주세요. | INVALID INPUT VALUE | 체형 타입의 형식에 맞게 입력해주세요. | 활동 수준의 형식에 맞게 입력해주세요.'
                code: 'BMI001 | BMI002 | BMI003 | COMMON002 | BMI003 | BMI005'
      401:
        description: '비로그인으로 접근했을 경우'
        content:
          application/json:
            example:
              errorCode:
                status: 401
                message: '로그인 후 이용해 주세요'
                code: 'COMMON008'
      500:
        description: '알 수 없는 오류'
        content:
          application/json:
            example:
              errorCode:
                status: 500
                message: Internal Server Error
                code: COMMON005

/bmi/me:
  get:
    tags: [BMI]
    produces:
      - application/json
    consumes:
      - application/json
    security:
      - bearerAuth: []
    responses:
      200:
        description: '내 bmi 조회 성공'
        content:
          application/json:
            example:
              data:
                createdAt: '2023-12-25T06:30:13.123Z'
                updatedAt: '2023-12-25T06:30:13.123Z'
                deletedAt: null
                id: 1
                userId: 1
                height: '180.0'
                weight: '100.0'
                bmiTarget: '19.0'
                targetDifference: '-161.0'
                bmrTarget: '2153.04'
                calories: '3714.0'
                activityType: 'veryInactive | Inactive | moderate | active | veryActive'
              status: 200
              message: '정상적으로 BMI가 조회되었습니다.'
      401:
        description: '비로그인으로 접근했을 경우'
        content:
          application/json:
            example:
              errorCode:
                status: 401
                message: '로그인 후 이용해 주세요'
                code: 'COMMON008'
      500:
        description: '알 수 없는 오류'
        content:
          application/json:
            example:
              errorCode:
                status: 500
                message: Internal Server Error
                code: COMMON005
