services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.production
    image: jihoon-production.kr.ncr.ntruss.com/jihoon-production:latest
    env_file:
      - .env.production
    ports:
      - '5001:5001'
    volumes:
      - ./:/app/
      - /app/node_modules
    environment:
      - TZ=Asia/Seoul
      - NODE_ENV=production
    command:
      - bash
      - -c
      - npm run production
    depends_on:
      - mysql
      - redis-server
      - rabbitmq

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: production
      MYSQL_DATABASE: production
      MYSQL_USER: production
      MYSQL_PASSWORD: production
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306

  redis-server:
    image: redis:latest
    command: redis-server --requirepass testuser --port 6379
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_ERLANG_COOKIE: 'aaaaaaaaaa'
    ports:
      - '5672:5672'
      - '15672:15672'
