services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '5001:5001'
    volumes:
      - ./:/app/
      - /app/node_modules
    environment:
      - TZ=Asia/Seoul
      - NODE_ENV=local
    command:
      - bash
      - -c
      - npm run local
    depends_on:
      - mysql
      - redis-server
      - rabbitmq

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: product
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306

  redis-server:
    image: redis:latest
    command: redis-server --requirepass testuser --port 6379
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_ERLANG_COOKIE: 'test_cookie'
      RABBITMQ_DEFAULT_USER: 'admin' # default : guest
      RABBITMQ_DEFAULT_PASS: 'admin'
    ports:
      - '5672:5672'
      - '15672:15672'
