services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.production
      args:
        - APPLICATION_IMAGE_NAME=${APPLICATION_IMAGE_NAME}
    image: ${APPLICATION_IMAGE_NAME}
    ports:
      - '5001:5001'
    volumes:
      - ./:/app/
      - /app/node_modules
    environment:
      - TZ=Asia/Seoul
      - NODE_ENV=production
    command:
      - bash
      - -c
      - npm run production
    depends_on:
      - mysql
      - redis-server

  mysql:
    image: ${MYSQL_IMAGE_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: production
      MYSQL_DATABASE: production
      MYSQL_USER: production
      MYSQL_PASSWORD: production
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306

  redis-server:
    image: ${REDIS_IMAGE_NAME}
    command: redis-server --requirepass testuser --port 6379
    ports:
      - '6379:6379'
