tags:
  name: Daily
  description: Daily Calorie Controller

definitions:
  Foods:
    type: object
    required:
      - foods
    properties:
      foods:
        type: array
        items:
          type: object
          properties:
            food:
              type: string
              description: 음식이름
            quantity:
              type: number
              description: 음식개수

/daily/record:
  post:
    tags: [Daily]
    produces:
      - application/json
    consumes:
      - application/json
    security:
      - bearerAuth: []
    requestBody:
      content:
        application/json:
          name: Foods
          required: true
          schema:
            $ref: '#/definitions/Foods'
    responses:
      201:
        description: '먹은 음식 등록 완료'
        content:
          application/json:
            example:
              status: 201
              message: '음식이 기록되었습니다.'
      400:
        description: '잘못된 데이터를 입력한 경우'
        content:
          application/json:
            example:
              errorCode:
                status: 400
                message: '음식 종류와 개수를 올바르게 입력해주세요.'
                code: 'DAILY001'
      401:
        description: '비로그인으로 접근했을 경우'
        content:
          application/json:
            example:
              errorCode:
                status: 401
                message: '로그인 후 이용해 주세요.'
                code: 'COMMON008'
      404:
        description: 'bmi 등록을 안했을 경우'
        content:
          application/json:
            example:
              errorCode:
                status: 404
                message: 'bmi 지수 데이터가 없습니다.'
                code: 'BMI005'
      500:
        description: '알 수 없는 오류'
        content:
          application/json:
            example:
              errorCode:
                status: 500
                message: Internal Server Error
                code: COMMON005

/daily/all:
  get:
    tags: [Daily]
    produces:
      - application/json
    consumes:
      - application/json
    security:
      - bearerAuth: []
    parameters:
      - in: path
        name: bmiId
        description: 체지방지수Id
        required: true
        schema:
          type: integer
    responses:
      200:
        description: '하루동안 먹은 음식'
        content:
          application/json:
            example:
              status: 200
              message: '하루동안 먹은 음식을 불러왔습니다.'
      401:
        description: '비로그인으로 접근했을 경우'
        content:
          application/json:
            example:
              errorCode:
                status: 401
                message: '로그인 후 이용해 주세요.'
                code: 'COMMON008'
      404:
        description: 'bmi 등록을 안했을 경우'
        content:
          application/json:
            example:
              errorCode:
                status: 404
                message: 'bmi 지수 데이터가 없습니다.'
                code: 'BMI005'
      500:
        description: '알 수 없는 오류'
        content:
          application/json:
            example:
              errorCode:
                status: 500
                message: Internal Server Error
                code: COMMON005

/daily/one:
  get:
    tags: [Daily]
    produces:
      - application/json
    consumes:
      - application/json
    security:
      - bearerAuth: []
    parameters:
      - in: path
        name: dailyFoodId
        description: 먹은음식Id
        required: true
        schema:
          type: integer
    responses:
      200:
        description: '하루동안 먹은 음식'
        content:
          application/json:
            example:
              status: 200
              message: '오늘 먹은 음식을 불러왔습니다.'
      401:
        description: '비로그인으로 접근했을 경우'
        content:
          application/json:
            example:
              errorCode:
                status: 401
                message: '로그인 후 이용해 주세요.'
                code: 'COMMON008'
      404:
        description: '오늘 먹은 음식 데이터가 없는 경우'
        content:
          application/json:
            example:
              errorCode:
                status: 404
                message: '오늘 먹은 음식 데이터가 없습니다.'
                code: 'DAILY002'
      500:
        description: '알 수 없는 오류'
        content:
          application/json:
            example:
              errorCode:
                status: 500
                message: Internal Server Error
                code: COMMON005
