tags:
  name: User
  description: User Controller

definitions:
  SignUp:
    type: object
    required:
      - email
      - password
      - phone
      - userType
      - sex
      - birth
    properties:
      email:
        type: string
        description: 이메일
      password:
        type: string
        description: 비밀번호
      phone:
        type: string
        description: 전화번호
      userType:
        type: string
        description: 유저타입
      sex:
        type: string
        description: 성별
      birth:
        type: string
        description: 생년월일

  SignUpAuth:
    type: object
    required:
      - phone
    properties:
      phone:
        type: string
        description: 전화번호

  SignIn:
    type: object
    required:
      - phone
      - password
    properties:
      phone:
        type: string
        description: 전화번호
      password:
        type: string
        description: 비밀번호

  ChangePassword:
    type: object
    required:
      - originPassword
      - changePassword
    properties:
      originPassword:
        type: string
        description: 기존 비밀번호
      changePassword:
        type: string
        description: 변경할 비밀번호

  WhithDrawal:
    type: object
    required:
      - password
    properties:
      password:
        type: string
        description: 비밀번호

/user/signup:
  post:
    tags: [User]
    produces:
      - application/json
    consumes:
      - application/json
    requestBody:
      content:
        application/json:
          name: SignUp
          required: true
          schema:
            $ref: '#/definitions/SignUp'
    responses:
      201:
        description: '회원가입'
        content:
          application/json:
            example:
              status: 201
              message: '정상적으로 회원가입 되었습니다.'
      400:
        description: '잘못된 데이터를 입력한 경우'
        content:
          application/json:
            example:
              errorCode:
                status: 400
                message: '이메일의 형식에 맞게 입력해주세요. | 비밀번호는 6자 이상 15자 이하의 영문+숫자이어야 합니다. | 핸드폰의 형식에 맞게 입력해주세요. | 유저 타입의 형식에 맞게 입력해주세요. | 생년월일을 제대로 입력해 주세요.'
                code: 'SIGNUP002 | SIGNUP003 | SIGNUP004 | SIGNUP006 | SIGNUP010'
      401:
        description: 'token이 없거나 유효하지 않음(비정상적 접근)'
        content:
          application/json:
            example:
              errorCode:
                status: 401
                message: 인증번호 데이터가 존재하지 않습니다. | 인증번호를 다시 발급해주세요
                code: SIGNUP007 | SIGNUP008
      403:
        description: '이미 회원가입한 유저'
        content:
          application/json:
            example:
              errorCode:
                status: 403
                message: 이미 회원가입한 아이디입니다.
                code: SIGNUP001
      404:
        description: 'redis auth 발급 안받은 유저'
        content:
          application/json:
            example:
              errorCode:
                status: 404
                message: PAGE NOT FOUND
                code: COMMON001
      500:
        description: '알 수 없는 오류'
        content:
          application/json:
            example:
              errorCode:
                status: 500
                message: Internal Server Error
                code: COMMON005
              fieldErrors: []

/user/signup/auth:
  post:
    tags: [User]
    produces:
      - application/json
    consumes:
      - application/json
    requestBody:
      content:
        application/json:
          name: SignUpAuth
          required: true
          schema:
            $ref: '#/definitions/SignUpAuth'
    responses:
      202:
        description: '인증번호 발급'
        content:
          application/json:
            example:
              status: 202
              message: '정상적으로 인증번호가 발급되었습니다.'
      400:
        description: '잘못된 데이터를 입력한 경우'
        content:
          application/json:
            example:
              errorCode:
                status: 400
                message: '핸드폰의 형식에 맞게 입력해주세요.'
                code: 'SIGNUP004'
      500:
        description: '알 수 없는 오류'
        content:
          application/json:
            example:
              errorCode:
                status: 500
                message: Internal Server Error
                code: COMMON005

/user/signin:
  post:
    tags: [User]
    produces:
      - application/json
    consumes:
      - application/json
    requestBody:
      content:
        application/json:
          name: SignIn
          required: true
          schema:
            $ref: '#/definitions/SignIn'
    responses:
      200:
        description: '로그인 완료'
        content:
          application/json:
            example:
              data:
                accessToken: 'testtoken1234'
                refreshToken: 'testtest'
              status: 200
              message: '정상적으로 로그인 되었습니다.'
      400:
        description: '잘못된 데이터를 입력한 경우'
        content:
          application/json:
            example:
              errorCode:
                status: 400
                message: '전화번호나 비밀번호가 일치하지 않습니다.'
                code: 'SIGNIN001'
      403:
        description: '토큰 발행 문제'
        content:
          application/json:
            example:
              errorCode:
                status: 403
                message: '토큰이 발급되지 않았습니다.'
                code: 'SIGNIN002'
      500:
        description: '알 수 없는 오류'
        content:
          application/json:
            example:
              errorCode:
                status: 500
                message: Internal Server Error
                code: COMMON005

/user/logout:
  post:
    tags: [User]
    produces:
      - application/json
    consumes:
      - application/json
    security:
      - bearerAuth: []
    responses:
      204:
        description: '로그아웃 성공'
        content:
          application/json:
            example:
              status: 204
              message: '정상적으로 로그아웃 되었습니다.'
      401:
        description: '잘못된 데이터를 입력한 경우'
        content:
          application/json:
            example:
              errorCode:
                status: 401
                message: '로그인 후 이용해 주세요'
                code: 'COMMON008'
      500:
        description: '알 수 없는 오류'
        content:
          application/json:
            example:
              errorCode:
                status: 500
                message: Internal Server Error
                code: COMMON005

/user/changepassword:
  patch:
    tags: [User]
    produces:
      - application/json
    consumes:
      - application/json
    security:
      - bearerAuth: []
    requestBody:
      content:
        application/json:
          name: ChangePassword
          required: true
          schema:
            $ref: '#/definitions/ChangePassword'

    responses:
      200:
        description: '비밀번호 변경'
        content:
          application/json:
            example:
              status: 200
              message: '정상적으로 비밀번호가 변경되었습니다.'
      400:
        description: '잘못된 데이터를 입력한 경우'
        content:
          application/json:
            example:
              errorCode:
                status: 400
                message: '비밀번호는 6자 이상 15자 이하의 영문+숫자이어야 합니다. | 기존의 비밀번호를 입력해주세요 | 기존의 비밀번호는 사용하실 수 없습니다.'
                code: 'SIGNUP003 | PASSWORD001 | PASSWORD002'
      401:
        description: '잘못된 데이터를 입력한 경우'
        content:
          application/json:
            example:
              errorCode:
                status: 401
                message: '로그인 후 이용해 주세요'
                code: 'COMMON008'
      500:
        description: '알 수 없는 오류'
        content:
          application/json:
            example:
              errorCode:
                status: 500
                message: Internal Server Error
                code: COMMON005

/user/withdrawal:
  delete:
    tags: [User]
    produces:
      - application/json
    consumes:
      - application/json
    security:
      - bearerAuth: []
    requestBody:
      content:
        application/json:
          name: WhithDrawal
          required: true
          schema:
            $ref: '#/definitions/WhithDrawal'
    responses:
      204:
        description: '로그아웃 성공'
        content:
          application/json:
            example:
              status: 204
              message: '정상적으로 로그아웃 되었습니다.'
      400:
        description: '잘못된 데이터를 입력한 경우'
        content:
          application/json:
            example:
              errorCode:
                status: 400
                message: '비밀번호는 6자 이상 15자 이하의 영문+숫자이어야 합니다. | 기존의 비밀번호를 입력해주세요'
                code: 'SIGNUP003 | PASSWORD001'
      401:
        description: '잘못된 데이터를 입력한 경우'
        content:
          application/json:
            example:
              errorCode:
                status: 401
                message: '로그인 후 이용해 주세요'
                code: 'COMMON008'
      500:
        description: '알 수 없는 오류'
        content:
          application/json:
            example:
              errorCode:
                status: 500
                message: Internal Server Error
                code: COMMON005
